trigger:
  - master
  - develop

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: github
      name: abatplus/smef-azure-pipeline-templates

variables:
  serviceName: "vswap-webview"

extends:
  template: docker/docker-build-and-push.yml@templates
  parameters:
    imageName: "abatplus/vswap"
    serviceName: $(serviceName)
    branchName: $(Build.SourceBranchName)
    tag: "$(serviceName)-$(Build.SourceBranchName)-0.0.5"
    dockerfile: "./src/Service.Dockerfile"
    buildContext: "./src/."